export const RURAL_AREA_FINDER_DEFAULT_RADIUS_METERS = 500;
export const RURAL_AREA_FINDER_MIN_RADIUS_METERS = 100;
export const RURAL_AREA_FINDER_MAX_RADIUS_METERS = 2000;
export const RURAL_AREA_FINDER_RADIUS_STEP_METERS = 50;
